### ISSUE TITLE
武器清单中近战武器里的 异端钩刃镰刀 是什么？

### ISSUE THREAD

**Issue by Simoncxm** [imhlq/EldenRingCheatSheetCN#14]
从来没有在任何渠道见到过这个武器。。请问是不是写错了？

**Comment by Simoncxm** [comment]
我在B站 wiki 上找到了这个武器的文本，但应该不是正常游戏能获得的物品，希望可以修改一下列表
https://wiki.biligame.com/eldenring/%E5%BC%82%E7%AB%AF%E9%92%A9%E5%88%83%E9%95%B0%E5%88%80%E6%96%87%E6%9C%AC

**Comment by imhlq** [comment]
已删除
