### ISSUE TITLE
传道士的制作笔记【３】 重复了一次

### ISSUE THREAD

**Issue by sakuyamaij** [imhlq/EldenRingCheatSheetCN#2]
还有 武器工匠的制作笔记【５】

**Comment by sakuyamaij** [comment]
还有 武器工匠的制作笔记【５】

**Comment by KrisCris** [comment]
<img width="312" alt="image" src="https://user-images.githubusercontent.com/38860226/160251977-7af6c5fc-202e-4250-a9dc-4bff14d7ca1c.png">

怪事，他们那个全物品列表的excel上也是重复的

**Comment by imhlq** [comment]
已修复
