### ISSUE TITLE
[全剧情流程清单]标记错误

### ISSUE THREAD

**Issue by GhostFIX** [imhlq/EldenRingCheatSheetCN#4]
“（白面具支线）在王城南侧山坡，找到柯林触发对话。
（白面具支线）在王城黄金树大教堂顶部拾取道具“黄金律法原本”，交给柯林或乌龟，学习“回归性原理”。在黄金树大教堂赐福出来电梯一楼，与雕像前官方建言互动。使用祷告“回归性原理”。再次查看官方建言。
（白面具支线）返回柯林处，与金面具对话。”
这三个任务应该是（金面具支线）

**Comment by imhlq** [comment]
最新提交已修复 2d63da8
